### PR TITLE
Create a homepage for the bucketlist app

### PR DESCRIPTION
**Pull request by JayKay24**

### CODE REVIEW

**Comment by AwuorMarvin** [comment]
Can we get a screenshot of the UI :)

**Comment by HawiCaesar** [comment]
Nice simple UI. Balsmaiq is good. I found it abit complicated though

**Comment by JayKay24** [comment]
bucketlist
@AwuorMarvin Here

**Comment by JayKay24** [comment]
Thanks @HawiCaesar

**Pull request merged**
