### PR TITLE
Add Classes to model my data on.

### PR DESCRIPTION
**Pull request by JayKay24**
I created an EntryForm and UserForm that will be implemented using Flask wtforms.

### CODE REVIEW

**Review by AwuorMarvin — COMMENTED** [review]
Looks fine by me...I'll need you to take me through what's going on here so I may implement a similar ideology in my app

**Comment by JayKay24** [comment]
Ok. There's this flask extension called wtforms that will automatically render form elements to be displayed complete with validation. I've also created some classes that will be used to hold the data for each instance but I will soon think of a more efficient data structure to hold multiple objects created from these classes. For now I just wanted to focus on just one instance of each class. I will handle multiple cases later. You may have noticed I also restructured my folders to accommodate building a new flask application.

**Comment by AwuorMarvin** [comment]
I'll look into the wtforms and how it works. Thanks for the info

**Comment by machariamarigi** [comment]
Consider using [flask_wtf](https://flask-wtf.readthedocs.io/en/stable/) library in conjunction with wtf_forms. It has a FlaskForm class that is more optimised for Flask projects. Also, consider using [blueprints](http://flask.pocoo.org/docs/0.12/blueprints/) to better structure the app.

**Comment by JayKay24** [comment]
Thank you for the info @machariamarigi. @AwuorMarvin lets heed to machariamarigi's advice.
@macharia could you perhaps let me know how in particular I could optimise my app to use blueprints?

**Comment by machariamarigi** [comment]
I'll drop you a PR when I'm through with mine.

**Pull request merged**
